from domain.exception.base_exception import BaseException

class NameError(BaseException):
    """Исключение для Name"""
    ...


